# Generated by Django 6.0.4 on 2026-05-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrimesterSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimester', models.CharField(max_length=10)),
                ('materia', models.CharField(max_length=100)),
                ('pendenti_iniziali', models.IntegerField()),
                ('pendenti_finali', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('trimester', 'materia')},
            },
        ),
    ]
